//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANGCA
    {
        public int IDTC { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<double> SOGIO { get; set; }
        public string MANV { get; set; }
        public Nullable<int> IDLOAICA { get; set; }
    
        public virtual LOAICA LOAICA { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
